### ISSUE TITLE
ICE Connection Failure

### ISSUE THREAD

**Issue by ZateFeto** [RationalCoding/multihack-brackets#56]
Only works between pc's in my own network, and when i try to use it between a pc of my network and a pc from another network it doesn't work.

Latest versions installed.

As soon as other guest/pc joins the room, in aprox 5 seconds 1 of us get's disconnected.

**Comment by t-mullen** [comment]
Brackets version and OS?

Does the web version work for you?

Can you post the console output?

**Comment by ZateFeto** [comment]
Release 1.10 build 1.10.0-17483 (release 024bee940) 
build timestamp: Wed Jul 05 2017 07:39:31 GMT+0100

OS Windows 10 64

Web version eliminates the need of that plugin/package

How to post the console output?

**Comment by t-mullen** [comment]
I'd like to see if the web version works for you to rule out a lot of network issues.

Debug > Shoe Developer Tools and copy-paste the console tab. Do this after attempting to connect to your friend.

**Comment by ZateFeto** [comment]
Sorry for the delay, Here is the update! :- 

Webversion didn't work between us with the same problem which is seconds later we disconnect from each other

regarding the console here it is :- 

<details>
    <summary>Console Log</summary>

```
Less has finished and no sheets were loaded.
/thirdparty/react.js:6541 Download the React DevTools for a better development experience: https://fb.me/react-devtools
/utils/DeprecationWarning.js:88 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at Object.<anonymous> (file:///C:/Users/ZateFeto%20BDK/AppData/Roaming/Brackets/extensions/user/multihack-brackets/lib/ui.js:12:19)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/utils/DeprecationWarning.js:88 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at Lang.get (file:///C:/Users/ZateFeto%20BDK/AppData/Roaming/Brackets/extensions/user/multihack-brackets/lib/lang/lang.js:19:12)
    at Object.<anonymous> (file:///C:/Users/ZateFeto%20BDK/AppData/Roaming/Brackets/extensions/user/multihack-brackets/lib/ui.js:13:25)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-]
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-[
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - start
main.js:36 click
main.js:97 handleStart
main.js:99 cena9000 3r23r
main.js:177 local change
main.js:178 awdawd Object
main.js:146 MH started
main.js:124 yjs ready
main.js:215 remote create file
editor.js:151 create file  awdawd
filesystem.js:54 created awdawd
main.js:126 sending project
main.js:183 local create file
main.js:215 remote create file
editor.js:151 create file  awdawd
filesystem.js:56 sent 0 of 5
filesystem.js:54 created cenap1
main.js:126 sending project
main.js:183 local create file
main.js:215 remote create file
editor.js:151 create file  cenap1
filesystem.js:169 setValue
filesystem.js:56 sent 1 of 5
filesystem.js:54 created main.css
main.js:126 sending project
main.js:183 local create file
main.js:215 remote create file
editor.js:151 create file  main.css
filesystem.js:169 setValue
filesystem.js:56 sent 2 of 5
filesystem.js:54 created Untitled-6
main.js:126 sending project
main.js:183 local create file
main.js:215 remote create file
editor.js:151 create file  Untitled-6
filesystem.js:169 setValue
filesystem.js:56 sent 3 of 5
filesystem.js:54 created screenshots/quick-edit.png
main.js:126 sending project
main.js:183 local create file
main.js:215 remote create file
editor.js:151 create file  screenshots/quick-edit.png
filesystem.js:169 setValue
filesystem.js:56 sent 4 of 5
main.js:115 voice
main.js:36 click
ui.js:99 Array[0]
/utils/DeprecationWarning.js:88 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at UI.openModal (file:///C:/Users/ZateFeto%20BDK/AppData/Roaming/Brackets/extensions/user/multihack-brackets/lib/ui.js:106:7)
    at HTMLAnchorElement.<anonymous> (file:///C:/Users/ZateFeto%20BDK/AppData/Roaming/Brackets/extensions/user/multihack-brackets/main.js:38:10)
main.js:36 click
ui.js:99 Array[0]
main.js:36 click
ui.js:99 Array[0]
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:215 remote create file
editor.js:151 create file  wdawdawd2
2main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
multihack-core.js:4158 Error: Ice connection failed.(…)(anonymous function) @ multihack-core.js:4158
multihack-core.js:4158 connection to peer closed
/utils/DeprecationWarning.js:88 Use brackets.getModule("thirdparty/mustache/mustache") instead of global Mustache.
    at Object.defineProperty.get (/brackets.js:123:32)
    at Object.create (file:///C:/Users/ZateFeto%20BDK/AppData/Roaming/Brackets/extensions/user/multihack-brackets/lib/tooltip.js:4:17)
    at UI.showLostConnection (file:///C:/Users/ZateFeto%20BDK/AppData/Roaming/Brackets/extensions/user/multihack-brackets/lib/ui.js:84:28)
    at RemoteManager.handleLostPeer (file:///C:/Users/ZateFeto%20BDK/AppData/Roaming/Brackets/extensions/user/multihack-brackets/main.js:232:8)
    at RemoteManager.EventEmitter.emit (file:///C:/Users/ZateFeto%20BDK/AppData/Roaming/Brackets/extensions/user/multihack-brackets/lib/npm/multihack-core.js:5349:48)
    at Connector.events (file:///C:/Users/ZateFeto%20BDK/AppData/Roaming/Brackets/extensions/user/multihack-brackets/lib/npm/multihack-core.js:5130:457)
    at Connector._onLostPeer (file:///C:/Users/ZateFeto%20BDK/AppData/Roaming/Brackets/extensions/user/multihack-brackets/lib/npm/multihack-core.js:4158:1934)
    at Connector._destroyPeer (file:///C:/Users/ZateFeto%20BDK/AppData/Roaming/Brackets/extensions/user/multihack-brackets/lib/npm/multihack-core.js:4158:913)
    at Peer.<anonymous> (file:///C:/Users/ZateFeto%20BDK/AppData/Roaming/Brackets/extensions/user/multihack-brackets/lib/npm/multihack-core.js:4158:653)
main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:169 local selection
editor.js:202 indexFromPos
editor.js:240 local change wdawdawd2 Object
main.js:177 local change
main.js:178 wdawdawd2 Object
main.js:169 local selection
main.js:36 click
ui.js:99 Array[0]
```
<details>

**Comment by t-mullen** [comment]
Okay, it is unfortunately a type of network error called an "ICE Failure". This is WebRTC's catch-all error for when a P2P connection cannot be established. It could be that one of you is behind a restrictive firewall, you have incompatible NATs, one client is blocking certain ports, or the ICE server is unreachable by one client. Sometimes the issue only lasts a few hours and will "go away".

This is a problem with WebRTC, but I'm looking into using a websocket fallback. Sorry it didn't work for you :/

**Comment by ZateFeto** [comment]
Can you tell me how to give it a try and solve this?

Port numbers to unblock? NAT setting to change?
How to make sure connection to ICE server is established?

Thanks in advance!

**Comment by t-mullen** [comment]
Debugging this can be rather difficult, but if you want to take a shot at it, open `chrome://webrtc-internals` in Chrome, then try the web version. The dump from that may give us a clue.

**Comment by t-mullen** [comment]
WebRTC is now only used if a connection can be made (in `4.3.1`). Can you try this and confirm it solves your issue?

WebSockets will be used as a fallback.

**Comment by ZateFeto** [comment]
Sadly my colleague is having others problems from his end atm therfor can't confirm if a connection can be made or not, I will leave a comment later if i can establish that with him.

Thanks for your effort @RationalCoding

**Comment by t-mullen** [comment]
Fairly certain this has been fixed by the new socket fallback, but feel free to reopen if you experience connection problems again.
